### ISSUE TITLE
Spinner disappear when used in long process for block

### ISSUE THREAD

**Issue by raphaklaus** [helloIAmPau/node-spinner#13] opened 2016-03-30 18:49 UTC
Hello! First, thanks for this awesome spinner! 

If there is a long processing block (like for) the spinner seems to disappear. Even if it was previously started.

Here is a gist: https://gist.github.com/raphaklaus/7b3c95346ba424cc735bc88bf4f14950

**Comment by helloIAmPau** [comment] 2016-03-31 12:39
Hi @raphaklaus 
I'm sorry, but I can't reproduce the bug on my box :S.

BTW if you mean that the spinner disappear AFTER the execution, try to change the `true` argument of the `stop()` function into `false`. That flag enable/disable the line cleaner.

**Comment by raphaklaus** [comment] 2016-03-31 13:08
Just clarifying things: when loop starts, the spinner do not show up. Only after loop ending, and for a tiny moment (because clear is `true`). Changing it to `false` the issue persist but after loop ending it appears frozen.

My env (Windows):
`$ node -v
v4.4.0`
`$ npm -v
2.7.0`

I've tested on Linux and the same situation occurs.
Can I get your box so I can test?

Please, test using this repo: https://github.com/raphaklaus/cli-spinner-issue 
Just run `npm install` and after `node index.js`

**Comment by helloIAmPau** [comment] 2016-03-31 13:52
Oh, ok. That is normal. You are locking the V8 vm with the for loop. You have to convert the for loop in something like this:
```javascript
"use strict";

const Spinner = require('cli-spinner').Spinner;

let downloadSpinner = new Spinner('Downloading.. %s');
downloadSpinner.setSpinnerString('|/-\\');
downloadSpinner.start();

let sum = 0;
let index = 0;

let loop = () => {
  setTimeout(() => {
    if(index === 9990000) {
      downloadSpinner.stop(true);
      return;
    };
    sum = sum * index / sum;
    index++;
    loop();
  }, 0);
};

loop();
```

If it is ok for you, I close the issue.

**Comment by raphaklaus** [comment] 2016-03-31 16:53
Why use `setTimeout()`?
Hmm, it works, but it's impossible since require modifications inside a processing block which could be in an external module, or in a worst scenario, demand this fix in many third-party modules... 

The ``for`` loop locks the ``setInterval()`` inside ``start()``, is what I've found. Probably it's normal behavior, but must be something less harmful to do...

**Comment by helloIAmPau** [comment] 2016-04-01 12:21
> Why use setTimeout()?
V8 is single thread and your for loop occupy that thread for all the time. Using the `setTimeout` you give back the control to the vm at every iteration so that it can do 'other things'.

I think you have to refactor your code having in mind how V8 works. (remember that there are async and webworker packages in node too).

**Closed by helloIAmPau** 2016-04-01 12:21 UTC
